### Start Pump Request
GET http://192.168.178.62:5000/startPump?slot=1&ml=100
Content-Type: application/json

### Start Pump Request 2
GET http://192.168.178.62:5000/startPump?slot=0&ml=100
Content-Type: application/json

### Order Drink with id=1
POST http://172.18.4.108:5000/api/drinks?id=1