version: "3.9"

services:
  mydb:
    image: "mysql:${MYSQL_IMAGE_VERSION}"
    container_name: "${MYSQL_CONTAINER_NAME}"
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${BACKEND_CONTAINER_NAME}"
    depends_on:
      - mydb
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.4.0/24

volumes:
  db-data: