services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Reads from .env file
      DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"