services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /tmp/app.db:/data/app.db
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=/data/app.db"
      # this will override ConnectionStrings.DefaultConnection in appsettings.json