###
POST http://localhost:8080/api/v1/drinks/create
Content-Type: application/json

{
  "name": "Sample Drink",
  "img": "sample-image-url.jpg",
  "toppings": "Chocolate drizzle",
  "ingredients": [
    {
      "name": "Espresso Shot",
      "amount": 2
    },
    {
      "name": "Milk",
      "amount": 1
    }
  ]
}

###
DELETE http://localhost:8080/api/v1/drinks/delete?id=3

###
PATCH http://localhost:5287/api/v1/ingredients/edit
Content-Type: application/json

{
  "IngredientId": 1,
  "IngredientName": "Updated Ingredient Name",
  "Quantity": 250
}

### Order a Custom Drink
POST http://localhost:5287/api/v1/drinks/orderCustomDrink
Content-Type: application/json

[
  {
    "IngredientName": "Vodka",
    "Ml": 50
  },
  {
    "IngredientName": "Orange Juice",
    "Ml": 150
  }
]

