// <auto-generated />
using System;
using Backend.Services.DatabaseService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250319195707_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Backend.Services.DatabaseService.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Toppings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drink");
                });

            modelBuilder.Entity("Backend.Services.DatabaseService.Models.DrinkIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrinkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IngredientName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientNameFK")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.HasIndex("IngredientName");

                    b.ToTable("DrinkIngredient");
                });

            modelBuilder.Entity("Backend.Services.DatabaseService.Models.DrinkOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DrinkID")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("DrinkID");

                    b.ToTable("DrinkOrder");
                });

            modelBuilder.Entity("Backend.Services.DatabaseService.Models.Ingredient", b =>
                {
                    b.Property<string>("IngredientName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PumpSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemainingAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientName");

                    b.HasIndex("PumpSlot");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("Backend.Services.DatabaseService.Models.Pump", b =>
                {
                    b.Property<int>("Slot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.HasKey("Slot");

                    b.ToTable("Pump");
                });

            modelBuilder.Entity("Backend.Services.DatabaseService.Models.DrinkIngredient", b =>
                {
                    b.HasOne("Backend.Services.DatabaseService.Models.Drink", "Drink")
                        .WithMany("DrinkIngredients")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Services.DatabaseService.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientName");

                    b.Navigation("Drink");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Backend.Services.DatabaseService.Models.DrinkOrder", b =>
                {
                    b.HasOne("Backend.Services.DatabaseService.Models.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkID");

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("Backend.Services.DatabaseService.Models.Ingredient", b =>
                {
                    b.HasOne("Backend.Services.DatabaseService.Models.Pump", "Pump")
                        .WithMany()
                        .HasForeignKey("PumpSlot");

                    b.Navigation("Pump");
                });

            modelBuilder.Entity("Backend.Services.DatabaseService.Models.Drink", b =>
                {
                    b.Navigation("DrinkIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
