// <auto-generated />
using System;
using HulaSwirl.Services.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HulaSwirl.Services.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250516085028_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("HulaSwirl.Services.DataAccess.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Toppings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drink");
                });

            modelBuilder.Entity("HulaSwirl.Services.DataAccess.Models.DrinkIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrinkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IngredientName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientNameFk")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.HasIndex("IngredientName");

                    b.ToTable("DrinkIngredient");
                });

            modelBuilder.Entity("HulaSwirl.Services.DataAccess.Models.DrinkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrinkId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.HasIndex("Username");

                    b.ToTable("DrinkOrder");
                });

            modelBuilder.Entity("HulaSwirl.Services.DataAccess.Models.Ingredient", b =>
                {
                    b.Property<string>("IngredientName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PumpSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemainingAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientName");

                    b.HasIndex("PumpSlot");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("HulaSwirl.Services.DataAccess.Models.Pump", b =>
                {
                    b.Property<int>("Slot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.HasKey("Slot");

                    b.ToTable("Pump");
                });

            modelBuilder.Entity("HulaSwirl.Services.DataAccess.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HulaSwirl.Services.DataAccess.Models.UserDrinkStatistic", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DrinkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserName", "DrinkId");

                    b.HasIndex("DrinkId");

                    b.ToTable("UserDrinkStat");
                });

            modelBuilder.Entity("HulaSwirl.Services.DataAccess.Models.DrinkIngredient", b =>
                {
                    b.HasOne("HulaSwirl.Services.DataAccess.Models.Drink", "Drink")
                        .WithMany("DrinkIngredients")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HulaSwirl.Services.DataAccess.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientName");

                    b.Navigation("Drink");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("HulaSwirl.Services.DataAccess.Models.DrinkOrder", b =>
                {
                    b.HasOne("HulaSwirl.Services.DataAccess.Models.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HulaSwirl.Services.DataAccess.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HulaSwirl.Services.DataAccess.Models.Ingredient", b =>
                {
                    b.HasOne("HulaSwirl.Services.DataAccess.Models.Pump", "Pump")
                        .WithMany()
                        .HasForeignKey("PumpSlot");

                    b.Navigation("Pump");
                });

            modelBuilder.Entity("HulaSwirl.Services.DataAccess.Models.UserDrinkStatistic", b =>
                {
                    b.HasOne("HulaSwirl.Services.DataAccess.Models.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HulaSwirl.Services.DataAccess.Models.User", "User")
                        .WithMany("DrinkStatistics")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HulaSwirl.Services.DataAccess.Models.Drink", b =>
                {
                    b.Navigation("DrinkIngredients");
                });

            modelBuilder.Entity("HulaSwirl.Services.DataAccess.Models.User", b =>
                {
                    b.Navigation("DrinkStatistics");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
